header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: CloudWeGo Authors

  paths:
    - '**/*.go'
    - '**/*.s'
    - '**/*.thrift'
    - '**/*.sh'
    - '**/Makefile'

  paths-ignore:
    - 'parser/AST.go'
    - 'parser/k-AST.go'
    - 'parser/thrift.peg.go'
    - 'plugin/protocol.go'
    - 'plugin/k-protocol.go'
    - 'test/golang/cases_and_options/thrifttest/a.thrift'

  comment: on-failure
