// Copyright 2023 CloudWeGo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package json_utils

import "encoding/json"

// jsonMarshaler customize json.Marshal as you like
type jsonMarshaler func(v interface{}) ([]byte, error)

var JSONFunc jsonMarshaler = json.Marshal

// ResetJSONMarshalFunc replace the JSON marshal func
// to all code which are generated by thriftgo.
// Usually, it is used in String() method.
func ResetJSONMarshalFunc(jn jsonMarshaler) {
	JSONFunc = jn
}
