package json_utils

import "encoding/json"

// jsonMarshaler customize json.Marshal as you like
type jsonMarshaler func(v interface{}) ([]byte, error)

var JSONFunc jsonMarshaler = json.Marshal

// ResetJSONMarshalFunc replace the JSON marshal func
// to all code which are generated by thriftgo.
// Usually, it is used in String() method.
func ResetJSONMarshalFunc(jn jsonMarshaler) {
	JSONFunc = jn
}
