// Copyright 2023 CloudWeGo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by thriftgo (0.3.0). DO NOT EDIT.

package thrift_reflection_test

import (
	"github.com/cloudwego/thriftgo/thrift_reflection"
)

func (p *IDCard) GetDescriptor() *thrift_reflection.StructDescriptor {
	return file_reflection_test_idl_thrift.GetStructDescriptor("IDCard")
}
func (p *Person) GetDescriptor() *thrift_reflection.StructDescriptor {
	return file_reflection_test_idl_thrift.GetStructDescriptor("Person")
}
func (p *A0) GetDescriptor() *thrift_reflection.StructDescriptor {
	return file_reflection_test_idl_thrift.GetStructDescriptor("A0")
}
func (p *A1) GetDescriptor() *thrift_reflection.StructDescriptor {
	return file_reflection_test_idl_thrift.GetStructDescriptor("A1")
}
func (p *A2) GetDescriptor() *thrift_reflection.StructDescriptor {
	return file_reflection_test_idl_thrift.GetStructDescriptor("A2")
}
func (p *A3) GetDescriptor() *thrift_reflection.StructDescriptor {
	return file_reflection_test_idl_thrift.GetStructDescriptor("A3")
}
func (p *B) GetDescriptor() *thrift_reflection.StructDescriptor {
	return file_reflection_test_idl_thrift.GetStructDescriptor("B")
}
func (p *B1) GetDescriptor() *thrift_reflection.StructDescriptor {
	return file_reflection_test_idl_thrift.GetStructDescriptor("B1")
}
func (p *C) GetDescriptor() *thrift_reflection.StructDescriptor {
	return file_reflection_test_idl_thrift.GetStructDescriptor("C")
}
func (p *D) GetDescriptor() *thrift_reflection.StructDescriptor {
	return file_reflection_test_idl_thrift.GetStructDescriptor("D")
}
func (p *D1) GetDescriptor() *thrift_reflection.StructDescriptor {
	return file_reflection_test_idl_thrift.GetStructDescriptor("D1")
}
func (p *D2) GetDescriptor() *thrift_reflection.StructDescriptor {
	return file_reflection_test_idl_thrift.GetStructDescriptor("D2")
}
func (p *E) GetDescriptor() *thrift_reflection.StructDescriptor {
	return file_reflection_test_idl_thrift.GetStructDescriptor("E")
}
func (p *F) GetDescriptor() *thrift_reflection.StructDescriptor {
	return file_reflection_test_idl_thrift.GetStructDescriptor("F")
}
func (p Gender) GetDescriptor() *thrift_reflection.EnumDescriptor {
	return file_reflection_test_idl_thrift.GetEnumDescriptor("Gender")
}
func (p Size) GetDescriptor() *thrift_reflection.EnumDescriptor {
	return file_reflection_test_idl_thrift.GetEnumDescriptor("Size")
}
func (p *MyUnion) GetDescriptor() *thrift_reflection.StructDescriptor {
	return file_reflection_test_idl_thrift.GetUnionDescriptor("MyUnion")
}
func (p *MyException) GetDescriptor() *thrift_reflection.StructDescriptor {
	return file_reflection_test_idl_thrift.GetExceptionDescriptor("MyException")
}
