// Copyright 2021 CloudWeGo
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package templates

// File .
var File = `// Code generated by thriftgo ({{.Version}}). DO NOT EDIT.
{{InsertionPoint "bof"}}

package {{.PkgName}}

import (
	{{- range $path, $alias := .Imports}}
	{{$alias }}"{{$path}}"
	{{- end}}
	{{InsertionPoint "imports"}}
)

{{template "Constant" .AST}}

{{- range .AST.Enums}}
{{template "Enum" .}}
{{- end}}

{{- range .AST.Typedefs}}
{{template "Typedef" .}}
{{- end}}

{{- range .AST.Structs}}
{{template "StructLike" .}}
{{- end}}

{{- range .AST.Unions}}
{{template "StructLike" .}}
{{- end}}

{{- range .AST.Exceptions}}
{{template "StructLike" .}}
{{- end}}

{{- range .AST.Services}}
{{template "Service" .}}
{{- end}}

{{- range .AST.Services}}
{{template "Processor" .}}
{{- end}}

{{- InsertionPoint "eof"}}
`
