name: Push Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Check License Header
        uses: apache/skywalking-eyes@v0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Unit Test
        run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./...

      - name: Lint
        run: |
          go vet -stdmethods=false $(go list ./...)   
          echo "go vet done!"

  codegen-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Prepare
        run: |
          go install
          go install github.com/cloudwego/kitex/tool/cmd/kitex@develop
          LOCAL_REPO=$(pwd)
          cd ..
          git clone https://github.com/cloudwego/kitex-tests.git 
          cd kitex-tests/codegen
          go mod init codegen-test
          go mod edit -replace=github.com/apache/thrift=github.com/apache/thrift@v0.13.0
          go mod edit -replace github.com/cloudwego/thriftgo=${LOCAL_REPO}
          go mod edit -replace github.com/cloudwego/kitex=github.com/cloudwego/kitex@develop
          go mod tidy
          bash -version
          bash ./codegen_install_check.sh
      - name: CodeGen
        run: |
          cd ../kitex-tests/codegen
          tree
          bash ./codegen_run.sh        
